name = "LabelledNumbers"
uuid = "f856a3a6-4152-4ec4-b2a7-02c1a55d7993"
authors = ["ITensor developers <support@itensor.org> and contributors"]
version = "0.1.1"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[weakdeps]
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"

[extensions]
LabelledNumbersBlockArraysExt = "BlockArrays"

[compat]
BlockArrays = "1.2.0"
Random = "1.10"
julia = "1.10"
